version: '3.9'

services:
  app:
    build: .
    container_name: test_app
    ports:
      - "8081:8080"
      - "8091:8090"
    environment:
      - TEST_MODE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      retries: 5
